### ISSUE TITLE
Can I use m3u8getter to download live stream video?

### ISSUE THREAD

**Issue by zydjohnHotmail** [qq940390/m3u8getter#2]
Hello:
I tried to use the binary in Windows 10 to download some live streaming m3u8 file, it has the following format:
https://video.maxline.by:444/x1/stream14/chunks.m3u8?nimblesessionid=4785912
But I got error: 
16:58:28 ： 开始下载： https://video.maxline.by:444/x1/stream14/chunks.m3u8?nimblesessionid=4785912
16:58:28 ： 远程文件不存在！
I can see this from VLC media player.
Let me know if you have some bug in your code. Please note: the url has some string after m3u8.
If you need more m3u8 url for testing, let me know, but most of  them expire within a few hours.
Thanks,

**Comment by qq940390** [comment]
I am not good at English, so if you need, I can open the source.

这个地址访问出现 HTTP ERROR 403 ，这说明可能需要权限验证，自己没什么时间维护这个工具，如果你需要，我可以开放源码。

**Comment by qq940390** [comment]
sorry I'm not good at English, but I open this url, it's returned 403 error.

**Comment by zydjohnHotmail** [comment]
Hi,
Try this one, but quick!
https://video.maxline.by:444/n1/stream61/chunks.m3u8?nimblesessionid=4798844

**Comment by qq940390** [comment]
I tried to fix that bug, try again?



--------------------
 冥王風


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qq940390/m3u8getter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qq940390/m3u8getter] Can I use m3u8getter to download live stream video? (#2)





 
Hi,
 Try this one, but quick!
 https://video.maxline.by:444/n1/stream61/chunks.m3u8?nimblesessionid=4798844

**Comment by zydjohnHotmail** [comment]
Hello:
I downloaded your repo again, and tried another one, the same error:
https://video1.maxline.by:444/o1/stream34/chunks.m3u8?nimblesessionid=3022140
17:25:33 ： 开始下载： https://video1.maxline.by:444/o1/stream34/chunks.m3u8?nimblesessionid=3022140
17:25:33 ： 远程文件不存在！

**Comment by qq940390** [comment]
sorry,my ability is limited.


---Original---
From: ***@***.***&gt;
Date: Tue, Jul 27, 2021 23:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qq940390/m3u8getter] Can I use m3u8getter to download live stream video? (#2)




 
Hello:
 I downloaded your repo again, and tried another one, the same error:
 https://video1.maxline.by:444/o1/stream34/chunks.m3u8?nimblesessionid=3022140
 17:25:33 ： 开始下载： https://video1.maxline.by:444/o1/stream34/chunks.m3u8?nimblesessionid=3022140
 17:25:33 ： 远程文件不存在！
